apiVersion: apps/v1
kind: Deployment
metadata:
  name: cash-note-system-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cash-note-system-app
  template:
    metadata:
      labels:
        app: cash-note-system-app
    spec:
      containers:
        - name: frontend
          image: ayeesuttiporn/cashnotesystem:latest
          ports:
            - containerPort: 80
