apiVersion: v1
kind: Service
metadata:
  name: cash-note-system-app
spec:
  type: NodePort
  selector:
    app: cash-note-system-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
